### ISSUE TITLE
Dataset Available?

### ISSUE THREAD

**Issue by adityaabothra** [SoccerNet/sn-tracking#1]
When would the tracking data be available? It's March 14th. Still waiting

**Comment by SilvioGiancola** [comment]
Hi @adityaabothra,

We are actively working on it with @kl2005ad @paulxinzhou and @cioppaanthony . Over the last month, we cleaned the data and built baselines for people like you to start with. We'll make an announcement soon regarding that challenge, hopefully in releasing a first version in a week or 2.

Best,

**Comment by ret-1** [comment]
The data is available now! @adityaabothra
