### ISSUE TITLE
HTTP Error 503: Service Unavailable 

### ISSUE THREAD

**Issue by sosoIrving** [SoccerNet/sn-tracking#15]
when I download this dataset, the error happened.
"This function should download train.zip for tracking - but train.zip was not uploaded on the server yet!"
Can you tell me how to solve this problem?

**Comment by paulxinzhou** [comment]
Hi @sosoIrving , can you be a little bit more specific about how you are downloading the dataset? What code you are running to download?

You could also double check with 
https://www.soccer-net.org/data
Tracking data and labels section?

**Comment by paulxinzhou** [comment]
@sosoIrving , the server is temporarily down. IT is fixing the issue and please let me know if it is not fixed within a few days.

**Comment by SilvioGiancola** [comment]
Our server is back online. Please give it a try now.
