### ISSUE TITLE
How to download the 12 games and annotated half?

### ISSUE THREAD

**Issue by mazatov** [SoccerNet/sn-tracking#5]
I followed the description and downloaded `train.zip`, 'test.zip` and `challenge.zip`. They seem to only contain the tracklets. 

How do I download the rest of the data? From what I understand I'm still missing a: 
 -  one complete halftime annotated with tracking data.
 - the complete videos for the 12 games.
 -

**Comment by SilvioGiancola** [comment]
Hi @mazatov,
We are not yet releasing the full videos of the 12 games, nor the tracklets for the complete half-time. 
We might release them after the challenge, but we will keep you posted on that.

**Comment by SilvioGiancola** [comment]
I will follow up on this thread once we release the 12 games

**Comment by egoodman92** [comment]
Thanks for the great dataset - when I downloaded the dataset, it appears that the "challenge" set does not have gameinfo.ini to indicate what type of event is occurring. Is there a plan to release this as well? Thanks!

**Comment by SilvioGiancola** [comment]
For the time being, I don't think we will release the type of event for the challenge set, as it might bias the tracking algorithms to learn specific tracking pattern based on that prior. If you are looking to ablate your method to different scenarios, I invite you to do it on a subset of the test set.

**Comment by dazzle-me** [comment]
Hello! Does tracking/train.zip also includes labels, such as ball/player (I can only see the bounding boxes), 
or does it only have the tracklets? 
I'm interested in implementing an object detector that is going to detect both players & ball, so I'll need labels for both players & ball, I wonder why doesn't annotation include such information?
![image](https://user-images.githubusercontent.com/57013219/186708459-c322ba81-c465-4ab5-b01c-e324a73ae14e.png)

**Comment by SilvioGiancola** [comment]
We have included in our latest version of SoccerNet pip package (https://pypi.org/project/SoccerNet/) a function to download the raw videos used in the public sets.
`mySoccerNetDownloader.downloadRAWVideo(dataset="SoccerNet-Tracking") # download single camera RAW Videos`
