### ISSUE TITLE
Does this dataset have classification labels?

### ISSUE THREAD

**Issue by dazzle-me** [SoccerNet/sn-tracking#6]
Thank you for publishing such a wonderful dataset, it's a lot of work and we appreciate it, however, I have a question if this dataset provides classification labels for given bounding boxes (player/ball), or am I missing something? 

I'm planning to train an object detection model which is going to detect players & ball, and I wonder where I can find such labels, for me it's natural that they should be there, but I can't find them :(

![image](https://user-images.githubusercontent.com/57013219/186708645-7b67d742-c859-41d8-b727-fbefcdf83be9.png)

**Comment by SilvioGiancola** [comment]
@paulxinzhou @kl2005ad can you please support that user with his issue?

**Comment by dazzle-me** [comment]
Thank you, I think I found nesessary information in ```gameinfo.ini``` file, it maps TrackletIDs to the corresponding class 
![image](https://user-images.githubusercontent.com/57013219/186932133-ea7367c4-66b9-4f05-8ceb-f0ce79bb0f37.png)
