### ISSUE TITLE
How to map gameID to soccernet video name?

### ISSUE THREAD

**Issue by ra1995** [SoccerNet/sn-tracking#7]
Hi, In the gameinfo.ini files, there is gameID field (which is an integer). How can I map this int value to the respective soccernet video in the main dataset? Thanks

**Comment by SilvioGiancola** [comment]
Hi, the videos are different from the 550 original SoccerNet games. They originate from a different subset, now available to download through the pip package. More information is available at https://github.com/SoccerNet/sn-tracking/issues/5.
